server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/task-management-realm
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/task-management-realm
spring.security.oauth2.client.registration.keycloak.client-id=task-management-client
spring.security.oauth2.client.registration.keycloak.client-secret=QuQrQIZ0FQgurXTb3mChGNwyLtXeWIpk
spring.security.oauth2.client.registration.keycloak.scope=openid

# Logging
logging.level.com.mentoring.taskmanagement=INFO
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG